import { createContext, useState, useContext, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Navigation & Header
    home: 'Home',
    services: 'Services',
    mediaCenter: 'Media Center',
    knowledgeCenter: 'Knowledge Center',
    digitalParticipation: 'Digital Participation',
    openData: 'Open Data',
    search: 'Search services...',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    account: 'Account',
    notLoggedIn: 'Not logged in',
    signInAccess: 'Sign in to access your application',
    language: 'Language',

    // ServiceLanding
    digitalService: 'Digital Service',
    housingArrearsRescheduling: 'Housing Arrears Rescheduling',
    serviceDesc1: 'This service allows UAE citizens to reschedule their outstanding housing loan payments based on their financial status and eligibility criteria.',
    serviceGuidelines: 'Service Guidelines',
    serviceDescription: 'Service Description',
    serviceDesc2: 'The Arrears Rescheduling service is designed to support homeowners who are experiencing temporary financial difficulties. This initiative allows for the restructuring of existing housing loan installments to better align with the applicant\'s current monthly income and financial obligations, ensuring long-term housing stability for UAE citizens.',
    estimatedTime: 'ESTIMATED TIME',
    estimatedTimeValue: '3-5 Working Days',
    serviceFee: 'SERVICE FEE',
    serviceFeeValue: 'AED 500',
    targetGroup: 'TARGET GROUP',
    targetGroupValue: 'UAE Citizens',
    eligibilityCriteria: 'Eligibility Criteria',
    eligibility1: 'The applicant must be a citizen of the United Arab Emirates.',
    eligibility2: 'Total monthly income should not exceed the thresholds defined by the Ministry.',
    eligibility3: 'The arrears must have accumulated due to documented financial hardship.',
    eligibility4: 'The property must be the primary residence of the applicant.',
    eligibility5: 'Previous rescheduling requests must be at least 24 months old.',
    eligibility6: 'Clear credit history report from relevant authorities.',
    readyToStart: 'Ready to start your application?',
    ensureDocuments: 'Ensure you have all required documents ready before proceeding.',
    startService: 'Start Service',

    // Login Page
    secureLogin: 'Secure Login',
    loginSubtitle: 'Login with your UAE Pass to access the Housing Arrears Rescheduling service',
    welcome: 'Welcome',
    loginDesc: 'Sign in to access your housing loan rescheduling application',
    loginWithUAEPass: 'Login with UAE Pass',
    aboutUAEPass: 'About UAE Pass',
    uaePassInfo: 'UAE Pass is a secure digital identity service. Your personal information is protected and only used for this service.',
    or: 'or',
    alternativeLoginMethods: 'Alternative Login Methods',
    digitalID: 'Digital ID',
    phoneVerification: 'Phone Verification',

    // ApplicantInfo Page
    breadcrumbHousing: 'Housing Services',
    breadcrumbArrears: 'Arrears Rescheduling',
    breadcrumbApplicant: 'Applicant Info',
    applicantDetails: 'Applicant Details',
    applicantDesc: 'Please provide your current financial information and employment status to proceed with the rescheduling request.',
    currentMonthlySalary: 'Current Monthly Salary (AED) *',
    salaryPlaceholder: 'e.g. 15000',
    salaryError: 'Monthly salary is required and must be greater than 0',
    salaryInfo: 'Include all basic allowances and recurring stipends.',
    residingAbroad: 'Are you currently residing abroad?',
    residingAbroadYes: 'Yes',
    residingAbroadNo: 'No',
    passportCopy: 'Passport Copy',
    passportUpload: 'Upload passport copy',
    passportError: 'Passport copy is required when residing abroad',
    hardshipRemarks: 'Hardship Remarks and Justification *',
    hardshipPlaceholder: 'Describe the financial hardship circumstances...',
    hardshipError: 'Hardship remarks and justification are required',
    words: 'words',
    declaration: 'Declaration *',
    declarationText: 'I declare that all information provided in this application is true and accurate to the best of my knowledge.',
    declarationError: 'You must agree to the declaration to proceed',
    continue: 'Continue',
    back: 'Back',

    // Documents Page
    breadcrumbDocuments: 'Documents',
    documentSubmission: 'Document Submission',
    documentDesc: 'Please upload the required documentation to process your request for rescheduling housing arrears. Ensure all files are clear and in PDF or JPG format.',
    salaryCertificate: 'Salary Certificate',
    salaryCertificateDesc: 'Latest official certificate showing basic salary and allowances, issued within the last 30 days.',
    bankStatement: 'Bank Statement',
    bankStatementDesc: 'Stamped personal bank statements for the last six consecutive months showing income deposits.',
    required: 'Required',
    optional: 'Optional',
    uploadDocument: 'Upload Document',
    clickToUpload: 'Click to upload',
    fileSizeError: 'File size exceeds 5MB limit',
    fileFormatError: 'Invalid file format. Please upload PDF, JPG, or PNG.',
    missingDocuments: 'Please upload all required documents',
    upload: 'Upload',
    submitted: 'Submitted',
    submit: 'Submit',

    // LoanSummary
    breadcrumbLoanSummary: 'Loan Summary',
    loanSummary: 'Loan Summary',
    loanSummaryDesc: 'Review your application details before submission.',
    monthlyIncome: 'Monthly Income',
    hardshipRemarksSummary: 'Hardship Remarks',
    abroadStatus: 'Residing Abroad',
    yes: 'Yes',
    no: 'No',

    // Results/Confirmation
    applicationSubmitted: 'Application Submitted',
    applicationSuccess: 'Your application has been successfully submitted.',
    referenceNumber: 'Reference Number',
    nextSteps: 'Next Steps',
    nextStepsDesc: 'You will receive a confirmation email shortly. Our team will review your application and contact you within 3-5 working days.',
    returnHome: 'Return to Home',

    // Status labels (shared across pages)
    statusInProgress: 'In Progress',
    statusAdditionalInfoRequired: 'Additional Information Required',
    statusUnderExpertReview: 'Under Expert Review',
    statusApproved: 'Approved',
    statusNotEligible: 'Not Eligible',

    // MyApplications page
    myApplications: 'My Applications',
    newApplication: 'New Application',
    loadingApplications: 'Loading your applications…',
    noApplicationsYet: 'No applications yet',
    noApplicationsDesc: 'You have not submitted any rescheduling requests.',
    startNewRequest: 'Start a New Request',
    arrearsReschedulingRequest: 'Arrears Rescheduling Request',
    submittedOn: 'Submitted',
    viewDetails: 'View Details',
    decisionLetter: 'Decision Letter',

    // ProfileConfirmation page
    breadcrumbConfirmIdentity: 'Confirm Identity',
    identityVerification: 'Identity Verification',
    identityVerificationDesc: 'The following information has been retrieved automatically from UAE PASS. Please verify it is correct before proceeding.',
    identityVerifiedUAEPass: 'Identity verified via UAE PASS',
    personalInformation: 'Personal Information',
    fullName: 'Full Name',
    fullNameArabic: 'Full Name (Arabic)',
    emiratesIdLabel: 'Emirates ID',
    dateOfBirth: 'Date of Birth',
    nationality: 'Nationality',
    gender: 'Gender',
    familyInformation: 'Family Information',
    maritalStatus: 'Marital Status',
    householdSizeLabel: 'Household Size',
    members: 'members',
    dependants: 'Dependants',
    contactEmployment: 'Contact & Employment',
    mobile: 'Mobile',
    emailLabel: 'Email',
    employerLabel: 'Employer',
    emirate: 'Emirate',
    moeiContactNote: 'If any of the above information is incorrect, please contact MOEI at 800 MOEI (6634) to update your records before proceeding.',
    backToLogin: 'Back to Login',
    confirmContinue: 'Confirm & Continue',

    // ReviewConfirm page
    breadcrumbReviewSubmit: 'Review & Submit',
    reviewYourApplication: 'Review Your Application',
    reviewDesc: 'Please review all details carefully before submitting your rescheduling request.',
    applicantSection: 'Applicant',
    nameLabel: 'Name',
    householdSizeShort: 'Household Size',
    loanDetailsSection: 'Loan Details',
    loanIdLabel: 'Loan ID',
    totalArrearsLabel: 'Total Arrears',
    monthsOverdueLabel: 'Months Overdue',
    monthsSuffix: 'months',
    currentEmiLabel: 'Current EMI',
    hardshipDeclarationSection: 'Hardship Declaration',
    reasonLabel: 'Reason',
    notSelectedGoBack: 'Not selected — go back to Documents',
    documentsSection: 'Documents',
    reviewDeclarationText: 'I declare that all information submitted in this application is accurate, true, and complete. I understand that submitting false information may result in rejection of the application and/or legal consequences under UAE law.',
    backToDocuments: 'Back to Documents',
    submitApplication: 'Submit Application',
    submittingEllipsis: 'Submitting…',
    pleaseAcceptDeclaration: 'Please accept the declaration before submitting.',
    hardshipMedical: 'Medical circumstances',
    hardshipIncomeReduction: 'Income reduction',
    hardshipAbroad: 'Temporary absence (abroad)',
    hardshipBereavement: 'Bereavement',
    hardshipUnemployment: 'Unemployment',
    hardshipOther: 'Other financial hardship',
    docSalaryCertificate: 'Salary Certificate',
    docBankStatement: 'Bank Statement (6 months)',
    docMedicalReport: 'Medical Report',
    docHardshipLetter: 'Hardship Letter',
    docPassport: 'Passport / Travel Proof',

    // LoanSummary page
    breadcrumbLoanDetails: 'Loan Details',
    yourLoanDetails: 'Your Loan Details',
    loanDetailsRetrievedDesc: 'The following loan data has been retrieved automatically from MOEI systems. Review your current financial standing before uploading your documents.',
    loanDetailsSummary: 'Loan Details Summary',
    retrievedFromMOEI: 'Retrieved from MOEI Central Systems',
    activeLoan: 'Active Loan',
    totalArrearsAmount: 'Total Arrears Amount',
    overdue: 'overdue',
    overdueInstallments: 'Overdue Installments',
    remainingBalance: 'Remaining Balance',
    priorReschedulings: 'Prior Reschedulings',
    unitAed: 'AED',
    unitMonths: 'Months',
    unitAedPerMonth: 'AED/Mo',
    unitOccurrences: 'Occurrence(s)',
    paymentHistory12: 'Payment History (last 12 months)',
    onTime: 'on-time',
    paidLegend: 'Paid',
    missedLegend: 'Missed',
    backToProfile: 'Back to Profile',

    // Documents (new) page
    breadcrumbDocumentsHardship: 'Documents & Hardship',
    documentsHardshipTitle: 'Documents & Hardship Declaration',
    documentsHardshipDesc: 'Upload your supporting documents and describe the circumstances that led to the payment arrears.',
    loanDataRetrieved: 'Loan data retrieved from MOEI systems',
    reasonForRescheduling: 'Reason for Rescheduling Request',
    selectMainReason: 'Select the main reason that led to the payment arrears.',
    additionalDetails: 'Additional details',
    provideAdditionalContext: 'Provide any additional context about your circumstances…',
    uploadDocuments: 'Upload Documents',
    maxFileSizeFormats: 'Max 5 MB per file · Accepted formats: PDF, JPG, PNG.',
    requiredDocuments: 'Required Documents',
    optionalSupportingDocuments: 'Optional Supporting Documents',
    backToLoanDetails: 'Back to Loan Details',
    reviewAndSubmit: 'Review & Submit',
    selectReasonError: 'Please select the reason for your rescheduling request.',
    fileTooLarge: 'File too large (max 5 MB):',
    unsupportedFormat: 'Unsupported format. Use PDF, JPG, or PNG.',
    pleaseUpload: 'Please upload:',
    replaceFile: 'Replace',
    hardshipMedicalLong: 'Medical circumstances (illness / disability)',
    hardshipIncomeReductionLong: 'Income reduction (salary decreased or job loss)',
    hardshipAbroadLong: 'Temporary absence (working or receiving treatment abroad)',
    hardshipBereavementLong: 'Bereavement (loss of spouse or main income source)',
    docSalaryCertificateFullDesc: 'Official salary certificate issued by your employer within the last 3 months.',
    docBankStatementFullDesc: 'Upload if available. If not provided, the system will automatically retrieve it via UAE Bank Data integration.',
    docAddMandate: 'ADD Mandate',
    docAddMandateFullDesc: 'Auto Direct Debit registration with your bank, verified via UAE PASS. Required to apply for rescheduling.',
    docAddMandateActive: 'Active — Verified via UAE PASS',
    docAddMandateNotSigned: 'Not Registered',
    docAddMandateBlockedDesc: 'You must register an Auto Direct Debit (ADD) mandate at your bank before applying for rescheduling. Please contact your bank to set this up, then return to proceed.',
    autoGeneratedDocuments: 'System-Generated Documents',
    addMandateTitle: 'Auto Direct Debit (ADD) Mandate',
    addMandateActiveDesc: 'Your ADD mandate is on file and will be used to collect the agreed monthly instalment once rescheduling is activated.',
    addMandateAgreedEmi: 'Agreed Monthly Instalment',
    addMandateFirstDeduction: 'First Deduction Date',
    addMandateBank: 'Bank',
    addMandateAccount: 'Account',
    docMedicalReportFullDesc: 'If your hardship is due to illness or disability.',
    docHardshipLetterFullDesc: 'A formal letter explaining your circumstances.',
    docPassportFullDesc: 'Required only if you are currently outside the UAE.',

    // SideNav component
    stepServiceOverview: 'Service Overview',
    arrearsReschedulingTitle: 'Arrears Rescheduling',
    applicationSteps: 'Application Steps',
    caseReferenceLabel: 'Case Reference:',
    contactSupport: 'Contact Support',

    // Confirmation page
    requestSubmittedSuccessfully: 'Request Submitted Successfully',
    applicationReceivedDesc: 'Your arrears rescheduling request has been received. You will be notified once a decision has been made.',
    whatHappensNext: 'What happens next?',
    applicationUnderReviewDesc: 'Your application is under review. Once a decision is made, you can view the full details and download your official decision letter from My Applications.',
    viewMyApplications: 'View My Applications',

    // Login page
    signWithUAEPass: 'Sign with UAE PASS',
    uaePassTrustedIdentity: 'A single trusted digital identity for all citizens, residents and visitors.',
    demoEnvPersonaHint: 'Demo environment — you will select a persona to continue',
    uaePassDemoMode: 'UAE PASS — Demo Mode',
    selectApplicantSimulate: 'Select an applicant to simulate UAE PASS authentication',
    liveDeploymentNote: 'In live deployment this step uses real UAE PASS API authentication',

    // ApplicationDetail page
    loadingApplication: 'Loading application…',
    applicationNotFound: 'Application not found.',
    backToMyApplications: 'Back to My Applications',
    downloadDecisionLetter: 'Download Decision Letter',
    processedIn: 'Processed in',
    previouslyUpTo5Days: '— previously up to 5 working days',
    uploadRequiredDocumentsTitle: 'Upload Required Documents',
    uploadRequiredDocumentsDesc: 'The system needs additional documents to continue processing your application.',
    documentsRequested: 'Documents Requested',
    clickToChooseFile: 'Click to choose file (PDF)',
    uploadingResubmitting: 'Uploading & re-submitting…',
    submitDocumentsButton: 'Submit Documents',
    documentsSubmittedSuccess: 'Documents submitted successfully',
    agentReanalysingDesc: 'The AI agent is re-analysing your application. This usually takes under a minute. Refresh this page in a moment to see your updated status.',
    yourNewRepaymentPlan: 'Your New Repayment Plan',
    newMonthlyInstallmentLabel: 'New Monthly Installment',
    planDurationLabel: 'Plan Duration',
    deductionRateLabel: 'Deduction Rate',
    ofSalary: 'of salary',
    twentyPctRuleLabel: '20% Rule',
    whatThisMeansForYou: 'What this means for you:',
    applicationDetailsSection: 'Application Details',
    applicantLabel: 'Applicant',
    hardshipReasonLabel: 'Hardship Reason',
    uaePassVerifiedLabel: 'UAE PASS Verified',
    loanSummarySection: 'Loan Summary',
    overdueMonthsLabel: 'Overdue Months',
    remainingPeriodLabel: 'Remaining Period',
    submittedDate: 'Submitted:',
    acceptPlan: 'Accept Plan',
    rejectPlan: 'Reject Proposed Plan',
    acceptPlanConfirm: 'Confirm & Accept Plan',
    rejectPlanTitle: 'Reject Proposed Plan',
    rejectPlanDesc: 'Tell us why you are rejecting this plan. Your case will be escalated to a human officer for review.',
    rejectReasonPlaceholder: 'Describe your concern or reason for rejection...',
    confirmRejection: 'Confirm Rejection',
    planAccepted: 'Plan Accepted',
    planAcceptedDesc: 'You have accepted the rescheduling plan. Your new payment schedule will take effect from the next deduction date.',
    planRejected: 'Escalated to Human Review',
    planRejectedDesc: 'Your case has been escalated. An officer will contact you within 3–5 working days.',
  },
  ar: {
    // Navigation & Header
    home: 'الرئيسية',
    services: 'الخدمات',
    mediaCenter: 'مركز الإعلام',
    knowledgeCenter: 'مركز المعرفة',
    digitalParticipation: 'المشاركة الرقمية',
    openData: 'البيانات المفتوحة',
    search: 'البحث عن الخدمات...',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    account: 'الحساب',
    notLoggedIn: 'لم تقم بتسجيل الدخول',
    signInAccess: 'قم بتسجيل الدخول للوصول إلى طلبك',
    language: 'اللغة',

    // ServiceLanding
    digitalService: 'خدمة رقمية',
    housingArrearsRescheduling: 'إعادة جدولة ديون الإسكان',
    serviceDesc1: 'تتيح هذه الخدمة لمواطني الإمارات إعادة جدولة مدفوعات قروض الإسكان المتعثرة بناءً على حالتهم المالية وتأهيلهم.',
    serviceGuidelines: 'إرشادات الخدمة',
    serviceDescription: 'وصف الخدمة',
    serviceDesc2: 'تم تصميم خدمة إعادة الجدولة لدعم مالكي العقارات الذين يواجهون صعوبات مالية مؤقتة. تسمح هذه المبادرة بإعادة هيكلة أقساط قرض الإسكان الحالية بما يتوافق بشكل أفضل مع دخل المتقدم الحالي والتزاماته المالية، مما يضمن الاستقرار السكني طويل الأجل لمواطني الإمارات.',
    estimatedTime: 'الوقت المقدر',
    estimatedTimeValue: '3-5 أيام عمل',
    serviceFee: 'رسوم الخدمة',
    serviceFeeValue: '500 درهم إماراتي',
    targetGroup: 'المجموعة المستهدفة',
    targetGroupValue: 'مواطنو الإمارات',
    eligibilityCriteria: 'معايير الأهلية',
    eligibility1: 'يجب أن يكون المتقدم مواطناً في الإمارات العربية المتحدة.',
    eligibility2: 'يجب ألا يتجاوز إجمالي الدخل الشهري الحد الأقصى المحدد من قبل الوزارة.',
    eligibility3: 'يجب أن تكون الديون قد تراكمت نتيجة مشقة مالية موثقة.',
    eligibility4: 'يجب أن تكون العقارات هي المسكن الرئيسي للمتقدم.',
    eligibility5: 'يجب أن تكون طلبات إعادة الجدولة السابقة قد مضى عليها 24 شهراً على الأقل.',
    eligibility6: 'تقرير رسمي نظيف من السجل الائتماني من السلطات المختصة.',
    readyToStart: 'هل أنت مستعد لبدء تطبيقك؟',
    ensureDocuments: 'تأكد من أن لديك جميع المستندات المطلوبة جاهزة قبل المتابعة.',
    startService: 'بدء الخدمة',

    // Login Page
    secureLogin: 'تسجيل دخول آمن',
    loginSubtitle: 'قم بتسجيل الدخول باستخدام بطاقة الهوية الرقمية للوصول إلى خدمة إعادة جدولة قروض الإسكان',
    welcome: 'أهلا وسهلا',
    loginDesc: 'قم بتسجيل الدخول للوصول إلى طلب إعادة جدولة قرض الإسكان الخاص بك',
    loginWithUAEPass: 'تسجيل الدخول عبر بطاقة الهوية الرقمية',
    aboutUAEPass: 'حول بطاقة الهوية الرقمية',
    uaePassInfo: 'بطاقة الهوية الرقمية هي خدمة هوية رقمية آمنة. معلوماتك الشخصية محمية ويتم استخدامها فقط لهذه الخدمة.',
    or: 'أو',
    alternativeLoginMethods: 'طرق تسجيل دخول بديلة',
    digitalID: 'هوية رقمية',
    phoneVerification: 'التحقق عبر الهاتف',

    // ApplicantInfo Page
    breadcrumbHousing: 'خدمات الإسكان',
    breadcrumbArrears: 'إعادة جدولة الديون',
    breadcrumbApplicant: 'معلومات المتقدم',
    applicantDetails: 'تفاصيل المتقدم',
    applicantDesc: 'يرجى تقديم معلومات وضعك المالي الحالي وحالة التوظيف لديك للمتابعة مع طلب إعادة الجدولة.',
    currentMonthlySalary: 'الراتب الشهري الحالي (درهم إماراتي) *',
    salaryPlaceholder: 'مثال: 15000',
    salaryError: 'الراتب الشهري مطلوب ويجب أن يكون أكبر من 0',
    salaryInfo: 'يشمل جميع البدلات الأساسية والمستحقات المتكررة.',
    residingAbroad: 'هل تقيم حالياً بالخارج؟',
    residingAbroadYes: 'نعم',
    residingAbroadNo: 'لا',
    passportCopy: 'نسخة جواز السفر',
    passportUpload: 'تحميل نسخة جواز السفر',
    passportError: 'نسخة جواز السفر مطلوبة عند الإقامة بالخارج',
    hardshipRemarks: 'ملاحظات المشقة المالية والتبرير *',
    hardshipPlaceholder: 'صف ظروف المشقة المالية...',
    hardshipError: 'ملاحظات المشقة المالية والتبرير مطلوبة',
    words: 'كلمات',
    declaration: 'إقرار *',
    declarationText: 'أقر بأن جميع المعلومات المقدمة في هذا الطلب صحيحة وصادقة بقدر معرفتي.',
    declarationError: 'يجب عليك الموافقة على الإقرار للمتابعة',
    continue: 'متابعة',
    back: 'رجوع',

    // Documents Page
    breadcrumbDocuments: 'المستندات',
    documentSubmission: 'تقديم المستندات',
    documentDesc: 'يرجى تحميل المستندات المطلوبة لمعالجة طلب إعادة جدولة ديون الإسكان. تأكد من أن جميع الملفات واضحة وبصيغة PDF أو JPG.',
    salaryCertificate: 'شهادة الراتب',
    salaryCertificateDesc: 'أحدث شهادة رسمية تبين الراتب الأساسي والبدلات، صادرة خلال آخر 30 يوماً.',
    bankStatement: 'كشف الحساب البنكي',
    bankStatementDesc: 'كشوف الحساب البنكي الشخصية المختومة لآخر ستة أشهر متتالية تبين إيداعات الدخل.',
    required: 'مطلوب',
    optional: 'اختياري',
    uploadDocument: 'تحميل المستند',
    clickToUpload: 'انقر لتحميل',
    fileSizeError: 'حجم الملف يتجاوز حد 5 ميجابايت',
    fileFormatError: 'صيغة ملف غير صحيحة. يرجى تحميل ملف PDF أو JPG أو PNG.',
    missingDocuments: 'يرجى تحميل جميع المستندات المطلوبة',
    upload: 'تحميل',
    submitted: 'تم التحميل',
    submit: 'إرسال',

    // LoanSummary
    breadcrumbLoanSummary: 'ملخص القرض',
    loanSummary: 'ملخص القرض',
    loanSummaryDesc: 'راجع تفاصيل طلبك قبل الإرسال.',
    monthlyIncome: 'الدخل الشهري',
    hardshipRemarksSummary: 'ملاحظات المشقة',
    abroadStatus: 'الإقامة بالخارج',
    yes: 'نعم',
    no: 'لا',

    // Results/Confirmation
    applicationSubmitted: 'تم إرسال الطلب',
    applicationSuccess: 'تم إرسال طلبك بنجاح.',
    referenceNumber: 'رقم المرجع',
    nextSteps: 'الخطوات التالية',
    nextStepsDesc: 'ستتلقى بريداً إلكترونياً للتأكيد قريباً. سيقوم فريقنا بمراجعة طلبك والاتصال بك خلال 3-5 أيام عمل.',
    returnHome: 'العودة إلى الرئيسية',

    // Status labels
    statusInProgress: 'قيد التنفيذ',
    statusAdditionalInfoRequired: 'معلومات إضافية مطلوبة',
    statusUnderExpertReview: 'قيد مراجعة الخبراء',
    statusApproved: 'معتمد',
    statusNotEligible: 'غير مؤهل',

    // MyApplications page
    myApplications: 'طلباتي',
    newApplication: 'طلب جديد',
    loadingApplications: 'جارٍ تحميل طلباتك…',
    noApplicationsYet: 'لا توجد طلبات بعد',
    noApplicationsDesc: 'لم تقدّم أي طلبات إعادة جدولة.',
    startNewRequest: 'بدء طلب جديد',
    arrearsReschedulingRequest: 'طلب إعادة جدولة المتأخرات',
    submittedOn: 'تاريخ التقديم',
    viewDetails: 'عرض التفاصيل',
    decisionLetter: 'خطاب القرار',

    // ProfileConfirmation page
    breadcrumbConfirmIdentity: 'تأكيد الهوية',
    identityVerification: 'التحقق من الهوية',
    identityVerificationDesc: 'تم استرداد المعلومات التالية تلقائيًا من هوية الإمارات الرقمية. يرجى التحقق من صحتها قبل المتابعة.',
    identityVerifiedUAEPass: 'تم التحقق من الهوية عبر هوية الإمارات الرقمية',
    personalInformation: 'المعلومات الشخصية',
    fullName: 'الاسم الكامل',
    fullNameArabic: 'الاسم الكامل (عربي)',
    emiratesIdLabel: 'بطاقة الهوية الإماراتية',
    dateOfBirth: 'تاريخ الميلاد',
    nationality: 'الجنسية',
    gender: 'الجنس',
    familyInformation: 'معلومات الأسرة',
    maritalStatus: 'الحالة الاجتماعية',
    householdSizeLabel: 'حجم الأسرة',
    members: 'أفراد',
    dependants: 'المعالون',
    contactEmployment: 'التواصل والتوظيف',
    mobile: 'الجوال',
    emailLabel: 'البريد الإلكتروني',
    employerLabel: 'جهة العمل',
    emirate: 'الإمارة',
    moeiContactNote: 'إذا كانت أي من المعلومات أعلاه غير صحيحة، يرجى التواصل مع الوزارة على الرقم 800 (6634) MOEI لتحديث سجلاتك قبل المتابعة.',
    backToLogin: 'العودة إلى تسجيل الدخول',
    confirmContinue: 'تأكيد والمتابعة',

    // ReviewConfirm page
    breadcrumbReviewSubmit: 'المراجعة والتقديم',
    reviewYourApplication: 'مراجعة طلبك',
    reviewDesc: 'يرجى مراجعة جميع التفاصيل بعناية قبل تقديم طلب إعادة الجدولة.',
    applicantSection: 'مقدم الطلب',
    nameLabel: 'الاسم',
    householdSizeShort: 'حجم الأسرة',
    loanDetailsSection: 'تفاصيل القرض',
    loanIdLabel: 'رقم القرض',
    totalArrearsLabel: 'إجمالي المتأخرات',
    monthsOverdueLabel: 'أشهر التأخر',
    monthsSuffix: 'أشهر',
    currentEmiLabel: 'القسط الشهري الحالي',
    hardshipDeclarationSection: 'إقرار الأوضاع الصعبة',
    reasonLabel: 'السبب',
    notSelectedGoBack: 'لم يتم الاختيار — عد إلى المستندات',
    documentsSection: 'المستندات',
    reviewDeclarationText: 'أقر بأن جميع المعلومات المقدمة في هذا الطلب دقيقة وصحيحة وكاملة. وأفهم أن تقديم معلومات خاطئة قد يؤدي إلى رفض الطلب و/أو التبعات القانونية بموجب قانون الإمارات العربية المتحدة.',
    backToDocuments: 'العودة إلى المستندات',
    submitApplication: 'تقديم الطلب',
    submittingEllipsis: 'جارٍ التقديم…',
    pleaseAcceptDeclaration: 'يرجى قبول الإقرار قبل التقديم.',
    hardshipMedical: 'ظروف طبية',
    hardshipIncomeReduction: 'تخفيض الدخل',
    hardshipAbroad: 'غياب مؤقت (خارج الدولة)',
    hardshipBereavement: 'وفاة ذوي',
    hardshipUnemployment: 'بطالة',
    hardshipOther: 'أوضاع مالية صعبة أخرى',
    docSalaryCertificate: 'شهادة الراتب',
    docBankStatement: 'كشف الحساب البنكي (6 أشهر)',
    docMedicalReport: 'التقرير الطبي',
    docHardshipLetter: 'خطاب الأوضاع الصعبة',
    docPassport: 'جواز السفر / إثبات السفر',

    // LoanSummary page
    breadcrumbLoanDetails: 'تفاصيل القرض',
    yourLoanDetails: 'تفاصيل قرضك',
    loanDetailsRetrievedDesc: 'تم استرداد بيانات القرض التالية تلقائيًا من أنظمة الوزارة. راجع وضعك المالي الحالي قبل تحميل مستنداتك.',
    loanDetailsSummary: 'ملخص تفاصيل القرض',
    retrievedFromMOEI: 'مسترد من الأنظمة المركزية للوزارة',
    activeLoan: 'قرض نشط',
    totalArrearsAmount: 'إجمالي مبلغ المتأخرات',
    overdue: 'متأخرة',
    overdueInstallments: 'الأقساط المتأخرة',
    remainingBalance: 'الرصيد المتبقي',
    priorReschedulings: 'عمليات الإعادة السابقة',
    unitAed: 'د.إ',
    unitMonths: 'أشهر',
    unitAedPerMonth: 'د.إ/شهر',
    unitOccurrences: 'مرة/مرات',
    paymentHistory12: 'سجل الدفع (آخر 12 شهراً)',
    onTime: 'في الموعد',
    paidLegend: 'مدفوع',
    missedLegend: 'متأخر',
    backToProfile: 'العودة إلى الملف الشخصي',

    // Documents (new) page
    breadcrumbDocumentsHardship: 'المستندات والإقرار',
    documentsHardshipTitle: 'المستندات وإقرار الأوضاع الصعبة',
    documentsHardshipDesc: 'قم بتحميل المستندات الداعمة ووصف الظروف التي أدت إلى تأخر المدفوعات.',
    loanDataRetrieved: 'تم استرداد بيانات القرض من أنظمة الوزارة',
    reasonForRescheduling: 'سبب طلب إعادة الجدولة',
    selectMainReason: 'اختر السبب الرئيسي الذي أدى إلى تأخر المدفوعات.',
    additionalDetails: 'تفاصيل إضافية',
    provideAdditionalContext: 'أضف أي سياق إضافي حول ظروفك…',
    uploadDocuments: 'تحميل المستندات',
    maxFileSizeFormats: 'الحد الأقصى 5 ميجابايت لكل ملف · الصيغ المقبولة: PDF، JPG، PNG.',
    requiredDocuments: 'المستندات المطلوبة',
    optionalSupportingDocuments: 'المستندات الداعمة الاختيارية',
    backToLoanDetails: 'العودة إلى تفاصيل القرض',
    reviewAndSubmit: 'المراجعة والتقديم',
    selectReasonError: 'يرجى اختيار سبب طلب إعادة الجدولة.',
    fileTooLarge: 'الملف كبير جداً (الحد الأقصى 5 ميجابايت):',
    unsupportedFormat: 'صيغة غير مدعومة. استخدم PDF أو JPG أو PNG.',
    pleaseUpload: 'يرجى تحميل:',
    replaceFile: 'استبدال',
    hardshipMedicalLong: 'ظروف طبية (مرض / إعاقة)',
    hardshipIncomeReductionLong: 'تخفيض الدخل (انخفاض الراتب أو فقدان العمل)',
    hardshipAbroadLong: 'غياب مؤقت (العمل أو تلقي العلاج خارج الدولة)',
    hardshipBereavementLong: 'وفاة ذوي (فقدان الزوج/ة أو مصدر الدخل الرئيسي)',
    docSalaryCertificateFullDesc: 'شهادة راتب رسمية صادرة من صاحب العمل خلال آخر 3 أشهر.',
    docBankStatementFullDesc: 'ارفع إذا كان متاحاً. في حال عدم رفعه، سيقوم النظام باسترداده تلقائياً عبر تكامل بيانات البنك الإماراتي.',
    docAddMandate: 'تفويض الخصم المباشر التلقائي',
    docAddMandateFullDesc: 'تسجيل الخصم المباشر التلقائي لدى بنكك، موثّق عبر هويتك الرقمية. مطلوب لتقديم طلب إعادة الجدولة.',
    docAddMandateActive: 'مفعّل — موثّق عبر الهوية الرقمية',
    docAddMandateNotSigned: 'غير مسجّل',
    docAddMandateBlockedDesc: 'يجب تسجيل تفويض الخصم المباشر التلقائي (ADD) لدى بنكك قبل تقديم طلب إعادة الجدولة. يرجى التواصل مع بنكك لإتمام التسجيل، ثم العودة للمتابعة.',
    autoGeneratedDocuments: 'المستندات المُنشأة تلقائياً',
    addMandateTitle: 'تفويض الخصم المباشر التلقائي (ADD)',
    addMandateActiveDesc: 'تفويض الخصم المباشر مسجّل لديك وسيُستخدم لتحصيل القسط الشهري المتفق عليه فور تفعيل إعادة الجدولة.',
    addMandateAgreedEmi: 'القسط الشهري المتفق عليه',
    addMandateFirstDeduction: 'تاريخ أول خصم',
    addMandateBank: 'البنك',
    addMandateAccount: 'الحساب',
    docMedicalReportFullDesc: 'إذا كانت الأوضاع الصعبة بسبب مرض أو إعاقة.',
    docHardshipLetterFullDesc: 'خطاب رسمي يشرح ظروفك.',
    docPassportFullDesc: 'مطلوب فقط إذا كنت خارج الإمارات حالياً.',

    // SideNav component
    stepServiceOverview: 'نظرة عامة على الخدمة',
    arrearsReschedulingTitle: 'إعادة جدولة المتأخرات',
    applicationSteps: 'خطوات الطلب',
    caseReferenceLabel: 'رقم الحالة:',
    contactSupport: 'التواصل مع الدعم',

    // Confirmation page
    requestSubmittedSuccessfully: 'تم تقديم الطلب بنجاح',
    applicationReceivedDesc: 'تم استلام طلب إعادة جدولة متأخراتك. سيتم إخطارك فور اتخاذ قرار.',
    whatHappensNext: 'ماذا يحدث بعد ذلك؟',
    applicationUnderReviewDesc: 'طلبك قيد المراجعة. بمجرد اتخاذ القرار، يمكنك عرض التفاصيل الكاملة وتحميل خطاب القرار الرسمي من طلباتي.',
    viewMyApplications: 'عرض طلباتي',

    // Login page
    signWithUAEPass: 'وقع بالهوية الرقمية',
    uaePassTrustedIdentity: 'هوية رقمية موحدة ومعتمدة لجميع المواطنين والمقيمين والزوار',
    demoEnvPersonaHint: 'بيئة تجريبية — سيُطلب منك اختيار شخصية للمتابعة',
    uaePassDemoMode: 'هوية الإمارات الرقمية — الوضع التجريبي',
    selectApplicantSimulate: 'اختر مقدم طلب لمحاكاة التحقق عبر هوية الإمارات الرقمية',
    liveDeploymentNote: 'في التشغيل الفعلي، تستخدم هذه الخطوة واجهة برمجة تطبيقات هوية الإمارات الرقمية الفعلية',

    // ApplicationDetail page
    loadingApplication: 'جارٍ تحميل الطلب…',
    applicationNotFound: 'الطلب غير موجود.',
    backToMyApplications: 'العودة إلى طلباتي',
    downloadDecisionLetter: 'تحميل خطاب القرار',
    processedIn: 'تمت المعالجة في',
    previouslyUpTo5Days: '— كان يستغرق حتى 5 أيام عمل',
    uploadRequiredDocumentsTitle: 'تحميل المستندات المطلوبة',
    uploadRequiredDocumentsDesc: 'يحتاج النظام إلى مستندات إضافية لمتابعة معالجة طلبك.',
    documentsRequested: 'المستندات المطلوبة',
    clickToChooseFile: 'انقر لاختيار ملف (PDF)',
    uploadingResubmitting: 'جارٍ التحميل وإعادة التقديم…',
    submitDocumentsButton: 'تقديم المستندات',
    documentsSubmittedSuccess: 'تم تقديم المستندات بنجاح',
    agentReanalysingDesc: 'يقوم النظام الذكي بإعادة تحليل طلبك. عادةً ما يستغرق ذلك أقل من دقيقة. يرجى تحديث الصفحة بعد لحظة لرؤية حالتك المحدثة.',
    yourNewRepaymentPlan: 'خطة السداد الجديدة',
    newMonthlyInstallmentLabel: 'القسط الشهري الجديد',
    planDurationLabel: 'مدة الخطة',
    deductionRateLabel: 'نسبة الاستقطاع',
    ofSalary: 'من الراتب',
    twentyPctRuleLabel: 'قاعدة 20%',
    whatThisMeansForYou: 'ماذا يعني هذا لك:',
    applicationDetailsSection: 'تفاصيل الطلب',
    applicantLabel: 'مقدم الطلب',
    hardshipReasonLabel: 'سبب الأوضاع الصعبة',
    uaePassVerifiedLabel: 'تم التحقق عبر هوية الإمارات الرقمية',
    loanSummarySection: 'ملخص القرض',
    overdueMonthsLabel: 'أشهر التأخر',
    remainingPeriodLabel: 'الفترة المتبقية',
    submittedDate: 'تاريخ التقديم:',
    acceptPlan: 'قبول الخطة',
    rejectPlan: 'رفض الخطة المقترحة',
    acceptPlanConfirm: 'تأكيد وقبول الخطة',
    rejectPlanTitle: 'رفض الخطة المقترحة',
    rejectPlanDesc: 'يرجى إخبارنا بسبب رفضك لهذه الخطة. سيُحال ملفك إلى موظف بشري للمراجعة.',
    rejectReasonPlaceholder: 'اذكر سبب أو مخاوفك من الرفض...',
    confirmRejection: 'تأكيد الرفض',
    planAccepted: 'تم قبول الخطة',
    planAcceptedDesc: 'لقد قبلت خطة إعادة الجدولة. سيبدأ جدول السداد الجديد من تاريخ الخصم القادم.',
    planRejected: 'تم التصعيد للمراجعة البشرية',
    planRejectedDesc: 'تم تصعيد حالتك. سيتواصل معك موظف خلال 3-5 أيام عمل.',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en'
    setLanguage(savedLanguage)
    applyLanguage(savedLanguage)
  }, [])

  const applyLanguage = (lang) => {
    // Save to localStorage
    localStorage.setItem('language', lang)

    // Apply direction to HTML element
    const htmlElement = document.documentElement
    if (lang === 'ar') {
      htmlElement.setAttribute('dir', 'rtl')
      htmlElement.setAttribute('lang', 'ar')
    } else {
      htmlElement.setAttribute('dir', 'ltr')
      htmlElement.setAttribute('lang', 'en')
    }
  }

  const changeLanguage = (lang) => {
    setLanguage(lang)
    applyLanguage(lang)
  }

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
