import { createContext, useState, useContext, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Navigation
    navDashboard: 'Dashboard',
    navApplications: 'Applications',
    navApprovedCases: 'Approved Cases',
    navNeedsReview: 'Needs Review',
    navPendingDocuments: 'Pending Documents',
    navRejectedCases: 'Rejected Cases',
    navAuditLogs: 'Audit Logs',
    navSettings: 'Settings',
    navApproved: 'Approved',
    navPendingDocs: 'Pending Docs',
    // Header
    headerTitle: 'Housing Arrears Rescheduling Dashboard',
    headerDept: 'Finance & Collection Department',
    headerEmployee: 'Employee Reviewer',
    moeiPortal: 'MOEI Employee Portal',
    language: 'Language',
    navigation: 'Navigation',
    // Sidebar AI agent
    aiAgentStatus: 'AI Agent Status',
    agentActiveDesc: 'Rescheduling agent is active and analyzing new submissions in real time.',
    // Dashboard page
    agentBadge: 'AI Agent for Rescheduling Housing Arrears',
    welcomeMsg: "Welcome back, Employee Reviewer. Here's where the rescheduling queue stands today.",
    agentDesc: 'The agent continuously analyzes incoming applications — validating documents, checking salary consistency, scoring risk, and recommending a rescheduling plan — so your team can focus on the cases that genuinely need human judgement.',
    loadingMetrics: 'Loading metrics...',
    recentApplications: 'Recent Applications',
    recentApplicationsSubtitle: 'Most recently updated cases across the queue',
    loadingApplications: 'Loading applications...',
    recentActivity: 'Recent Activity',
    recentActivitySubtitle: 'Latest status changes from the AI agent',
    loadingActivity: 'Loading activity...',
    // SummaryCards
    totalApplications: 'Total Applications',
    totalApplicationsHint: 'All cases currently in the queue',
    approvedAutomatically: 'Approved Automatically',
    approvedAutomaticallyHint: 'Cleared by the AI agent with no review needed',
    needsHumanReview: 'Needs Human Review',
    needsHumanReviewHint: 'Flagged by the agent for employee judgement',
    pendingDocuments: 'Pending Documents',
    pendingDocumentsHint: 'Awaiting missing or incomplete submissions',
    rejectedNotEligible: 'Rejected / Not Eligible',
    rejectedNotEligibleHint: 'Determined ineligible for rescheduling',
    avgConfidenceScore: 'Average Confidence Score',
    avgConfidenceScoreHint: 'Mean AI confidence across all cases',
    // ApplicationsTable columns
    colApplicationId: 'Application ID',
    colApplicantName: 'Applicant Name',
    colCurrentSalary: 'Current Salary',
    colArrearsAmount: 'Arrears Amount',
    colOverdueMonths: 'Overdue Months',
    colRiskLevel: 'Risk Level',
    colStatus: 'Status',
    colHumanReview: 'Human Review',
    colConfidenceScore: 'Confidence Score',
    colLastUpdated: 'Last Updated',
    noApplicationsMatch: 'No applications match the current filters',
    tryAdjustingFilters: 'Try adjusting or resetting the filters above.',
    reviewRequired: 'Required',
    reviewNotNeeded: 'Not Needed',
    viewDetails: 'View Details',
    monthAbbr: 'mo.',
    // FiltersBar
    search: 'Search',
    nameOrAppId: 'Name or application ID…',
    filterStatus: 'Status',
    filterRiskLevel: 'Risk Level',
    filterHumanReview: 'Human Review',
    filterLastUpdated: 'Last Updated',
    anyTime: 'Any Time',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    demoPlaceholder: 'Demo placeholder — mock data is static',
    showing: 'Showing',
    matchingApplications: 'matching application(s)',
    resetFilters: 'Reset filters',
    statusAll: 'All Statuses',
    statusApprovedAuto: 'Approved Automatically',
    statusNeedsReview: 'Needs Human Review',
    statusPendingDocs: 'Pending Documents',
    statusSalaryMismatch: 'Salary Mismatch',
    statusMedicalReview: 'Medical Hardship Review',
    statusIncomplete: 'Incomplete Application',
    statusRejectedFilter: 'Rejected / Not Eligible',
    riskAll: 'All Risk Levels',
    riskLow: 'Low Risk',
    riskMedium: 'Medium Risk',
    riskHigh: 'High Risk',
    riskIncomplete: 'Incomplete',
    reviewAll: 'All Cases',
    reviewRequiredFilter: 'Review Required',
    reviewNotNeededFilter: 'No Review Needed',
    // Page titles / descriptions (props to ApplicationsExplorer)
    pageApplicationsTitle: 'Applications',
    pageApplicationsDesc: 'Every rescheduling request currently tracked by the AI agent, with full filtering and search.',
    pageApplicationsEmpty: 'No applications are currently in the queue.',
    pageApprovedTitle: 'Approved Cases',
    pageApprovedDesc: 'Applications the AI agent cleared automatically — no employee review was required.',
    pageApprovedEmpty: 'No applications have been automatically approved yet.',
    pageNeedsReviewTitle: 'Needs Review',
    pageNeedsReviewDesc: "Cases the AI agent flagged for an employee's judgement — borderline scores, salary mismatches, or hardship circumstances.",
    pageNeedsReviewEmpty: 'No cases are currently waiting on a human reviewer.',
    pagePendingDocsTitle: 'Pending Documents',
    pagePendingDocsDesc: 'Applications where the AI agent could not complete validation because required documents are missing or the submission is incomplete.',
    pagePendingDocsEmpty: 'Every application currently has a complete document set.',
    pageRejectedTitle: 'Rejected Cases',
    pageRejectedDesc: 'Applications the AI agent determined ineligible for rescheduling.',
    pageRejectedEmpty: 'No applications have been rejected yet.',
    // ApplicationsExplorer
    casesInView: 'case(s) in this view',
    loadingCases: 'Loading cases...',
    nothingHere: 'Nothing here right now',
    // ApplicationDetails page
    loadingCaseDetails: 'Loading case details...',
    applicationNotFound: 'Application not found',
    backToList: 'Back to list',
    caseFile: 'Case File:',
    back: 'Back',
    // ApplicationDetailsPanel
    requestAdditionalDocuments: 'Request Additional Documents',
    selectDocumentsNeeded: 'Select which documents the applicant needs to provide:',
    docOptSalaryCertificate: 'Salary Certificate',
    docOptBankStatement: 'Bank Statement (last 6 months)',
    docOptMedicalReport: 'Medical report or disability certificate',
    docOptHardshipLetter: 'Formal hardship / circumstances letter',
    docOptPassport: 'Passport copy / travel stamp (if abroad)',
    docOptOther: 'Other (specify below)',
    additionalInstructions: 'Additional instructions for the applicant (optional)…',
    cancel: 'Cancel',
    sendRequest: 'Send Request',
    identityVerifiedUAEPASS: 'Identity verified via UAE PASS',
    emiratesId: 'Emirates ID:',
    household: 'Household:',
    members: 'members',
    pctConfidence: '% confidence',
    wasWorkingDays: 'was 5 working days',
    fieldAppId: 'Application ID',
    fieldCurrentSalary: 'Current Salary',
    fieldEmployer: 'Employer',
    fieldCurrentEmi: 'Current Monthly EMI',
    fieldArrearsAmount: 'Arrears Amount',
    fieldOverdueMonths: 'Overdue Months',
    fieldRemainingBalance: 'Remaining Balance',
    fieldLastUpdated: 'Last Updated',
    systemAnalysis: 'System Analysis Results',
    caseSummary: 'Case Summary',
    incomeAnalysis: 'Income Analysis',
    incomeSalaryCurrent: 'Current Salary',
    incomeSalaryOrigination: 'Salary at Origination',
    incomeChange: 'Income Change',
    perFamilyMember: 'Per Family Member',
    thresholdAbove: '≥ AED 2,500 threshold',
    thresholdBelow: '< AED 2,500 threshold',
    ruleComplianceChecks: 'Rule Compliance Checks',
    rule20Pct: '20% Income Cap Rule',
    ruleRepaymentPeriod: 'Repayment Period Rule',
    ruleCrossCheck: 'Income Cross-Check (V2)',
    rulePass: 'PASS',
    ruleFail: 'FAIL',
    proposedPlan: 'Proposed Rescheduling Plan',
    planNewEmi: 'New EMI (During Plan)',
    planEmiAfter: 'EMI After Plan',
    planDuration: 'Plan Duration',
    planDeductionRate: 'Deduction Rate',
    reasoning: 'Reasoning',
    documents: 'Documents',
    identity: 'Identity',
    documentsReceived: 'Documents Received',
    missingDocuments: 'Missing Documents',
    noDocumentsYet: 'No documents received yet',
    noMissingDocuments: 'No missing documents — file is complete',
    validationResults: 'Validation Results',
    salaryMatchStatus: 'Salary Match Status',
    documentCompleteness: 'Document Completeness',
    crossDocConsistency: 'Cross-Document Consistency',
    identifiedIssues: 'Identified Issues',
    employeeActions: 'Employee Actions',
    updateAuditTrail: 'Update application state and write to the audit trail.',
    reAnalyze: 'Re-Analyze',
    approve: 'Approve',
    reject: 'Reject',
    requestDocuments: 'Request Documents',
    sendToHumanReview: 'Send to Human Review',
    planCurrentEmi: 'Current EMI',
    auditTrail: 'Audit Trail',
    noCase: 'No case selected',
    viewDetailsCTA: 'Choose “View Details” on any application in the table to open its full case file here.',
    processingMsg: 'Processing application… this may take 20–30 seconds.',
    documentRequestSent: 'Document request sent and audit log updated.',
    actionSaved: 'saved.',
    // PATH_LABELS
    pathP1: 'P1 — Increase installment',
    pathP2: 'P2 — Partial increase',
    pathP3: 'P3 — Maintain installment, spread arrears',
    pathP4: 'P4 — Transfer arrears to end of loan',
    pathP5: 'P5 — Escalated to human review',
    // AgentTracePanel
    agentTrace: 'Agent Execution Trace',
    agentTraceDesc: 'Every tool call, result, error, and Claude reasoning block from the last agent run.',
    refresh: 'Refresh',
    loadingTrace: 'Loading trace…',
    noEventsToShow: 'No events to show.',
    agentStarted: 'Agent started',
    agentFinished: 'Agent finished',
    claudeReasoning: 'Claude reasoning',
    // buildAuditTrail
    auditSubmitted: 'Application submitted',
    auditUploaded: 'Documents uploaded',
    auditValidation: 'System validation completed',
    auditRecommendation: 'Rescheduling plan generated',
    auditFinalStatus: 'Final status assigned',
    auditReviewPending: 'Employee review pending',
    auditReviewNotRequired: 'Employee review not required',
    // StatusBadge labels
    statusApproved: 'Approved',
    statusNeedsReviewBadge: 'Needs Review',
    statusPendingDocuments: 'Pending Documents',
    statusSalaryMismatch: 'Salary Mismatch',
    statusMedicalReview: 'Medical Review',
    statusIncompleteBadge: 'Incomplete',
    statusRejected: 'Rejected',
    // RiskBadge labels
    riskLowLabel: 'Low Risk',
    riskMediumLabel: 'Medium Risk',
    riskHighLabel: 'High Risk',
    riskIncompleteLabel: 'Incomplete',
    // AuditLogs page
    auditLogsTitle: 'Audit Logs',
    auditLogsDesc: 'A chronological, system-wide trail of every step the AI agent and the case lifecycle took — useful for compliance reviews and explaining how a decision was reached.',
    searchAuditLogs: 'Search applicant, ID, or event detail…',
    allEvents: 'All Events',
    showingXofY: 'Showing',
    ofY: 'of',
    loggedEvents: 'logged events',
    noLogEntries: 'No log entries match your filters',
    eventSubmitted: 'Application Submitted',
    eventUploaded: 'Documents Uploaded',
    eventValidation: 'AI Validation Completed',
    eventRecommendation: 'Recommendation Generated',
    eventStatus: 'Final Status Assigned',
    eventReview: 'Review Routing Decision',
    // Settings page
    settingsTitle: 'Settings',
    settingsDesc: 'Personal preferences for your reviewer workspace. This is a visual-only demo screen — nothing is persisted to a server.',
    reviewerProfile: 'Reviewer Profile',
    reviewerProfileSubtitle: 'How your account appears across the portal',
    employeeReviewer: 'Employee Reviewer',
    financeCollection: 'Finance & Collection Department',
    roleCaseReviewer: 'Role: Case Reviewer · Access level: Standard',
    department: 'Department',
    financeCollectionShort: 'Finance & Collection',
    workingHours: 'Working Hours',
    workingHoursValue: 'Sun–Thu, 08:00–16:00',
    notificationPreferences: 'Notification Preferences',
    notificationPreferencesSubtitle: "Choose how you'd like to be notified about case activity",
    emailAlertLabel: 'Email me when a case needs review',
    emailAlertHint: 'Sent whenever the AI agent routes a new case to your queue',
    dailyRemindersLabel: 'Daily review reminders',
    dailyRemindersHint: 'A short morning summary of cases awaiting your decision',
    autoRefreshLabel: 'Auto-refresh dashboard data',
    autoRefreshHint: 'Automatically reload summary cards and tables every few minutes',
    displayPreferences: 'Display Preferences',
    displayPreferencesSubtitle: 'Adjust how the case tables are presented',
    compactTablesLabel: 'Compact table rows',
    compactTablesHint: 'Show more applications per screen by reducing row height',
    defaultLandingPage: 'Default landing page',
    defaultLandingPageHint: 'Choose which view opens when you sign in',
    optionDashboard: 'Dashboard Overview',
    optionAllApplications: 'All Applications',
    optionNeedsReview: 'Needs Review Queue',
    aboutWorkspace: 'About This Workspace',
    aboutWorkspaceSubtitle: 'Project context for this demo',
    aboutLine1: 'Designed to demonstrate the employee-facing side of an AI agent that reviews housing-arrears rescheduling requests.',
    aboutLine2: "Frontend-only React + Vite + Tailwind project — every figure you see comes from local mock data designed to mirror the agent's structured JSON output.",
    aboutLine3: 'No external services, databases, or APIs are contacted from this screen or anywhere in the app.',
    savePreferences: 'Save Preferences',
    preferencesSaved: 'Preferences saved locally for this demo session.',
    // Layout footer
    frontendDemoOnly: 'Frontend demo only, all data is mocked.',
  },
  ar: {
    // Navigation
    navDashboard: 'لوحة التحكم',
    navApplications: 'الطلبات',
    navApprovedCases: 'الحالات المعتمدة',
    navNeedsReview: 'تحتاج مراجعة',
    navPendingDocuments: 'مستندات معلقة',
    navRejectedCases: 'الحالات المرفوضة',
    navAuditLogs: 'سجلات المراجعة',
    navSettings: 'الإعدادات',
    navApproved: 'معتمدة',
    navPendingDocs: 'مستندات معلقة',
    // Header
    headerTitle: 'لوحة تحكم إعادة جدولة ديون الإسكان',
    headerDept: 'قسم المالية والتحصيل',
    headerEmployee: 'مراجع الحالات',
    moeiPortal: 'بوابة موظفي الوزارة',
    language: 'اللغة',
    navigation: 'التنقل',
    // Sidebar AI agent
    aiAgentStatus: 'حالة الوكيل الذكي',
    agentActiveDesc: 'الوكيل الذكي نشط ويحلل الطلبات الواردة في الوقت الفعلي.',
    // Dashboard page
    agentBadge: 'الوكيل الذكي لإعادة جدولة ديون الإسكان',
    welcomeMsg: 'مرحباً بك مجدداً، مراجع الحالات. هذه هي حالة قائمة انتظار إعادة الجدولة اليوم.',
    agentDesc: 'يحلل الوكيل باستمرار الطلبات الواردة — التحقق من المستندات، وفحص اتساق الراتب، وتقييم المخاطر، والتوصية بخطة إعادة جدولة — حتى يتمكن فريقك من التركيز على الحالات التي تحتاج فعلاً إلى حكم بشري.',
    loadingMetrics: 'جارٍ تحميل المقاييس...',
    recentApplications: 'أحدث الطلبات',
    recentApplicationsSubtitle: 'الحالات المحدَّثة حديثاً عبر القائمة',
    loadingApplications: 'جارٍ تحميل الطلبات...',
    recentActivity: 'النشاط الأخير',
    recentActivitySubtitle: 'أحدث تغييرات الحالة من الوكيل الذكي',
    loadingActivity: 'جارٍ تحميل النشاط...',
    // SummaryCards
    totalApplications: 'إجمالي الطلبات',
    totalApplicationsHint: 'جميع الحالات الموجودة حالياً في القائمة',
    approvedAutomatically: 'معتمدة تلقائياً',
    approvedAutomaticallyHint: 'تمت الموافقة عليها بواسطة الوكيل الذكي دون الحاجة إلى مراجعة',
    needsHumanReview: 'تحتاج مراجعة بشرية',
    needsHumanReviewHint: 'أشار إليها الوكيل لحكم الموظف',
    pendingDocuments: 'مستندات معلقة',
    pendingDocumentsHint: 'في انتظار المستندات الناقصة أو غير المكتملة',
    rejectedNotEligible: 'مرفوضة / غير مؤهلة',
    rejectedNotEligibleHint: 'تبيّن عدم أهليتها لإعادة الجدولة',
    avgConfidenceScore: 'متوسط درجة الثقة',
    avgConfidenceScoreHint: 'متوسط ثقة الذكاء الاصطناعي عبر جميع الحالات',
    // ApplicationsTable columns
    colApplicationId: 'رقم الطلب',
    colApplicantName: 'اسم المتقدم',
    colCurrentSalary: 'الراتب الحالي',
    colArrearsAmount: 'مبلغ المتأخرات',
    colOverdueMonths: 'أشهر التأخر',
    colRiskLevel: 'مستوى المخاطرة',
    colStatus: 'الحالة',
    colHumanReview: 'مراجعة بشرية',
    colConfidenceScore: 'درجة الثقة',
    colLastUpdated: 'آخر تحديث',
    noApplicationsMatch: 'لا توجد طلبات تطابق الفلاتر الحالية',
    tryAdjustingFilters: 'حاول تعديل الفلاتر أو إعادة ضبطها.',
    reviewRequired: 'مطلوبة',
    reviewNotNeeded: 'غير مطلوبة',
    viewDetails: 'عرض التفاصيل',
    monthAbbr: 'شهر',
    // FiltersBar
    search: 'بحث',
    nameOrAppId: 'الاسم أو رقم الطلب...',
    filterStatus: 'الحالة',
    filterRiskLevel: 'مستوى المخاطرة',
    filterHumanReview: 'مراجعة بشرية',
    filterLastUpdated: 'آخر تحديث',
    anyTime: 'أي وقت',
    last7Days: 'آخر 7 أيام',
    last30Days: 'آخر 30 يوماً',
    last90Days: 'آخر 90 يوماً',
    demoPlaceholder: 'عرض تجريبي — البيانات ثابتة',
    showing: 'عرض',
    matchingApplications: 'طلب(ات) مطابق(ة)',
    resetFilters: 'إعادة ضبط الفلاتر',
    statusAll: 'جميع الحالات',
    statusApprovedAuto: 'معتمدة تلقائياً',
    statusNeedsReview: 'تحتاج مراجعة بشرية',
    statusPendingDocs: 'مستندات معلقة',
    statusSalaryMismatch: 'عدم تطابق الراتب',
    statusMedicalReview: 'مراجعة الحالة الطبية',
    statusIncomplete: 'طلب غير مكتمل',
    statusRejectedFilter: 'مرفوضة / غير مؤهلة',
    riskAll: 'جميع مستويات المخاطرة',
    riskLow: 'مخاطرة منخفضة',
    riskMedium: 'مخاطرة متوسطة',
    riskHigh: 'مخاطرة عالية',
    riskIncomplete: 'غير مكتمل',
    reviewAll: 'جميع الحالات',
    reviewRequiredFilter: 'مراجعة مطلوبة',
    reviewNotNeededFilter: 'لا حاجة لمراجعة',
    // Page titles / descriptions
    pageApplicationsTitle: 'الطلبات',
    pageApplicationsDesc: 'جميع طلبات إعادة الجدولة التي يتابعها الوكيل الذكي حالياً، مع إمكانية الفلترة والبحث الكامل.',
    pageApplicationsEmpty: 'لا توجد طلبات في قائمة الانتظار حالياً.',
    pageApprovedTitle: 'الحالات المعتمدة',
    pageApprovedDesc: 'الطلبات التي أجاز الوكيل الذكي معالجتها تلقائياً — لم يكن هناك حاجة لمراجعة من الموظف.',
    pageApprovedEmpty: 'لم تتم الموافقة التلقائية على أي طلبات حتى الآن.',
    pageNeedsReviewTitle: 'تحتاج مراجعة',
    pageNeedsReviewDesc: 'الحالات التي أشار إليها الوكيل الذكي لحكم الموظف — درجات حدية، أو عدم تطابق الرواتب، أو ظروف صعبة.',
    pageNeedsReviewEmpty: 'لا توجد حالات تنتظر حالياً مراجعة بشرية.',
    pagePendingDocsTitle: 'مستندات معلقة',
    pagePendingDocsDesc: 'الطلبات التي تعذّر على الوكيل الذكي إتمام التحقق منها لأن المستندات المطلوبة مفقودة أو الإرسال غير مكتمل.',
    pagePendingDocsEmpty: 'جميع الطلبات لديها مجموعة مستندات كاملة حالياً.',
    pageRejectedTitle: 'الحالات المرفوضة',
    pageRejectedDesc: 'الطلبات التي رأى الوكيل الذكي أنها غير مؤهلة لإعادة الجدولة.',
    pageRejectedEmpty: 'لم يتم رفض أي طلبات حتى الآن.',
    // ApplicationsExplorer
    casesInView: 'حالة/حالات في هذا العرض',
    loadingCases: 'جارٍ تحميل الحالات...',
    nothingHere: 'لا يوجد شيء هنا الآن',
    // ApplicationDetails page
    loadingCaseDetails: 'جارٍ تحميل تفاصيل الحالة...',
    applicationNotFound: 'الطلب غير موجود',
    backToList: 'العودة إلى القائمة',
    caseFile: 'ملف الحالة:',
    back: 'رجوع',
    // ApplicationDetailsPanel
    requestAdditionalDocuments: 'طلب مستندات إضافية',
    selectDocumentsNeeded: 'اختر المستندات التي يحتاج مقدم الطلب إلى تقديمها:',
    docOptSalaryCertificate: 'شهادة الراتب',
    docOptBankStatement: 'كشف الحساب البنكي (آخر 6 أشهر)',
    docOptMedicalReport: 'تقرير طبي أو شهادة إعاقة',
    docOptHardshipLetter: 'خطاب رسمي للأوضاع الصعبة / الظروف',
    docOptPassport: 'نسخة جواز السفر / ختم السفر (إذا كان خارج الدولة)',
    docOptOther: 'أخرى (حدد أدناه)',
    additionalInstructions: 'تعليمات إضافية لمقدم الطلب (اختياري)...',
    cancel: 'إلغاء',
    sendRequest: 'إرسال الطلب',
    identityVerifiedUAEPASS: 'تم التحقق من الهوية عبر هوية الإمارات الرقمية',
    emiratesId: 'بطاقة الهوية الإماراتية:',
    household: 'الأسرة:',
    members: 'أفراد',
    pctConfidence: '% ثقة',
    wasWorkingDays: 'كان 5 أيام عمل',
    fieldAppId: 'رقم الطلب',
    fieldCurrentSalary: 'الراتب الحالي',
    fieldEmployer: 'جهة العمل',
    fieldCurrentEmi: 'القسط الشهري الحالي',
    fieldArrearsAmount: 'مبلغ المتأخرات',
    fieldOverdueMonths: 'أشهر التأخر',
    fieldRemainingBalance: 'الرصيد المتبقي',
    fieldLastUpdated: 'آخر تحديث',
    systemAnalysis: 'نتائج التحليل الآلي',
    caseSummary: 'ملخص الحالة',
    incomeAnalysis: 'تحليل الدخل',
    incomeSalaryCurrent: 'الراتب الحالي',
    incomeSalaryOrigination: 'الراتب عند منح القرض',
    incomeChange: 'تغير الدخل',
    perFamilyMember: 'لكل فرد من أفراد الأسرة',
    thresholdAbove: '≥ حد 2,500 درهم',
    thresholdBelow: '< حد 2,500 درهم',
    ruleComplianceChecks: 'فحوصات الامتثال للقواعد',
    rule20Pct: 'قاعدة حد 20% من الدخل',
    ruleRepaymentPeriod: 'قاعدة فترة السداد',
    ruleCrossCheck: 'التحقق المتقاطع من الدخل (V2)',
    rulePass: 'ناجح',
    ruleFail: 'فاشل',
    proposedPlan: 'خطة إعادة الجدولة المقترحة',
    planNewEmi: 'القسط الجديد (خلال الخطة)',
    planEmiAfter: 'القسط بعد الخطة',
    planDuration: 'مدة الخطة',
    planDeductionRate: 'نسبة الاستقطاع',
    reasoning: 'التبرير',
    documents: 'المستندات',
    identity: 'الهوية',
    documentsReceived: 'المستندات المستلمة',
    missingDocuments: 'المستندات المفقودة',
    noDocumentsYet: 'لم تُستلم أي مستندات بعد',
    noMissingDocuments: 'لا مستندات مفقودة — الملف مكتمل',
    validationResults: 'نتائج التحقق',
    salaryMatchStatus: 'حالة تطابق الراتب',
    documentCompleteness: 'اكتمال المستندات',
    crossDocConsistency: 'التوافق بين المستندات',
    identifiedIssues: 'المشكلات المحددة',
    employeeActions: 'إجراءات الموظف',
    updateAuditTrail: 'تحديث حالة الطلب والكتابة في سجل المراجعة.',
    reAnalyze: 'إعادة التحليل',
    approve: 'موافقة',
    reject: 'رفض',
    requestDocuments: 'طلب مستندات',
    sendToHumanReview: 'إرسال للمراجعة البشرية',
    planCurrentEmi: 'القسط الشهري الحالي',
    auditTrail: 'مسار المراجعة',
    noCase: 'لم يتم اختيار حالة',
    viewDetailsCTA: 'اختر "عرض التفاصيل" على أي طلب في الجدول لفتح ملف الحالة الكامل هنا.',
    processingMsg: 'جارٍ معالجة الطلب... قد يستغرق هذا 20–30 ثانية.',
    documentRequestSent: 'تم إرسال طلب المستندات وتحديث سجل المراجعة.',
    actionSaved: 'تم حفظه.',
    // PATH_LABELS
    pathP1: 'P1 — زيادة القسط',
    pathP2: 'P2 — زيادة جزئية',
    pathP3: 'P3 — الحفاظ على القسط، توزيع المتأخرات',
    pathP4: 'P4 — نقل المتأخرات إلى نهاية القرض',
    pathP5: 'P5 — تصعيد للمراجعة البشرية',
    // AgentTracePanel
    agentTrace: 'تتبع تنفيذ الوكيل',
    agentTraceDesc: 'كل استدعاء أداة، ونتيجة، وخطأ، وكتلة استدلال كلود من آخر تشغيل للوكيل.',
    refresh: 'تحديث',
    loadingTrace: 'جارٍ تحميل التتبع...',
    noEventsToShow: 'لا توجد أحداث للعرض.',
    agentStarted: 'بدأ الوكيل',
    agentFinished: 'انتهى الوكيل',
    claudeReasoning: 'استدلال كلود',
    // buildAuditTrail
    auditSubmitted: 'تم تقديم الطلب',
    auditUploaded: 'تم تحميل المستندات',
    auditValidation: 'اكتمل التحقق الآلي',
    auditRecommendation: 'تم إنشاء خطة إعادة الجدولة',
    auditFinalStatus: 'تم تحديد الحالة النهائية',
    auditReviewPending: 'مراجعة الموظف معلقة',
    auditReviewNotRequired: 'لا يلزم مراجعة الموظف',
    // StatusBadge labels
    statusApproved: 'معتمد',
    statusNeedsReviewBadge: 'تحتاج مراجعة',
    statusPendingDocuments: 'مستندات معلقة',
    statusSalaryMismatch: 'عدم تطابق الراتب',
    statusMedicalReview: 'مراجعة طبية',
    statusIncompleteBadge: 'غير مكتمل',
    statusRejected: 'مرفوض',
    // RiskBadge labels
    riskLowLabel: 'مخاطرة منخفضة',
    riskMediumLabel: 'مخاطرة متوسطة',
    riskHighLabel: 'مخاطرة عالية',
    riskIncompleteLabel: 'غير مكتمل',
    // AuditLogs page
    auditLogsTitle: 'سجلات المراجعة',
    auditLogsDesc: 'مسار زمني شامل لكل خطوة اتخذها الوكيل الذكي ودورة حياة الحالة — مفيد لمراجعات الامتثال وشرح كيفية الوصول إلى القرار.',
    searchAuditLogs: 'البحث عن المتقدم، أو المعرف، أو تفاصيل الحدث...',
    allEvents: 'جميع الأحداث',
    showingXofY: 'عرض',
    ofY: 'من',
    loggedEvents: 'أحداث مسجلة',
    noLogEntries: 'لا توجد إدخالات في السجل تطابق الفلاتر',
    eventSubmitted: 'تم تقديم الطلب',
    eventUploaded: 'تم رفع المستندات',
    eventValidation: 'اكتمل التحقق بالذكاء الاصطناعي',
    eventRecommendation: 'تم إنشاء التوصية',
    eventStatus: 'تم تحديد الحالة النهائية',
    eventReview: 'قرار توجيه المراجعة',
    // Settings page
    settingsTitle: 'الإعدادات',
    settingsDesc: 'تفضيلات شخصية لمساحة عمل المراجع. هذه شاشة عرض تجريبي فقط — لا شيء يحفظ على الخادم.',
    reviewerProfile: 'ملف تعريف المراجع',
    reviewerProfileSubtitle: 'كيف يظهر حسابك في البوابة',
    employeeReviewer: 'مراجع الحالات',
    financeCollection: 'قسم المالية والتحصيل',
    roleCaseReviewer: 'الدور: مراجع الحالات · مستوى الوصول: عادي',
    department: 'القسم',
    financeCollectionShort: 'المالية والتحصيل',
    workingHours: 'ساعات العمل',
    workingHoursValue: 'الأحد–الخميس، 08:00–16:00',
    notificationPreferences: 'تفضيلات الإشعارات',
    notificationPreferencesSubtitle: 'اختر كيف تريد أن يتم إخطارك بنشاط الحالات',
    emailAlertLabel: 'أرسل لي بريداً إلكترونياً عند الحاجة إلى مراجعة حالة',
    emailAlertHint: 'يُرسَل كلما وجّه الوكيل الذكي حالة جديدة إلى قائمتك',
    dailyRemindersLabel: 'تذكيرات المراجعة اليومية',
    dailyRemindersHint: 'ملخص صباحي موجز للحالات التي تنتظر قرارك',
    autoRefreshLabel: 'تحديث تلقائي لبيانات لوحة التحكم',
    autoRefreshHint: 'إعادة تحميل البطاقات الملخصة والجداول تلقائياً كل بضع دقائق',
    displayPreferences: 'تفضيلات العرض',
    displayPreferencesSubtitle: 'ضبط طريقة عرض جداول الحالات',
    compactTablesLabel: 'صفوف جداول مضغوطة',
    compactTablesHint: 'عرض المزيد من الطلبات في الشاشة عن طريق تقليل ارتفاع الصف',
    defaultLandingPage: 'الصفحة الافتراضية عند الدخول',
    defaultLandingPageHint: 'اختر العرض الذي يفتح عند تسجيل الدخول',
    optionDashboard: 'نظرة عامة على لوحة التحكم',
    optionAllApplications: 'جميع الطلبات',
    optionNeedsReview: 'قائمة انتظار المراجعة',
    aboutWorkspace: 'حول هذه البيئة',
    aboutWorkspaceSubtitle: 'سياق المشروع لهذا العرض التجريبي',
    aboutLine1: 'مصمم لإظهار الجانب المخصص للموظف من وكيل ذكاء اصطناعي يراجع طلبات إعادة جدولة متأخرات الإسكان.',
    aboutLine2: 'مشروع React + Vite + Tailwind للواجهة الأمامية فقط — كل رقم تراه يأتي من بيانات وهمية محلية مصممة لمحاكاة مخرجات JSON المنظمة للوكيل.',
    aboutLine3: 'لا توجد خدمات خارجية أو قواعد بيانات أو واجهات برمجية يتم الاتصال بها من هذه الشاشة أو أي مكان في التطبيق.',
    savePreferences: 'حفظ التفضيلات',
    preferencesSaved: 'تم حفظ التفضيلات محلياً لهذه الجلسة التجريبية.',
    // Layout footer
    frontendDemoOnly: 'عرض تجريبي للواجهة الأمامية فقط، جميع البيانات وهمية.',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('dashboardLanguage') || 'en',
  )

  useEffect(() => {
    document.documentElement.setAttribute('lang', language)
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr')
    localStorage.setItem('dashboardLanguage', language)
  }, [language])

  const t = (key) => translations[language]?.[key] ?? translations.en[key] ?? key

  return (
    <LanguageContext.Provider value={{ language, changeLanguage: setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
