"""
Pydantic v2 models for rescheduling decisions and final recommendations.

Generated by A5 (Policy Path Engine) and A6 (Decision & Rationale Agent).
"""

from decimal import Decimal
from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel


class ReschedulingPlan(BaseModel):
    """Financial plan computed by the deterministic rule engine (A5)."""
    path: Literal["P1", "P2", "P3", "P4", "P5"]
    proposed_emi: Decimal
    emi_during: Decimal                  # EMI including arrears spread during plan
    emi_after: Decimal                   # EMI after rescheduling period ends
    monthly_arrears_spread: Decimal      # 0 for P4 and P5
    duration_months: int                 # 0 for P4 (arrears deferred to end)
    new_term_months: int | None = None   # only set when term changes
    arrears_deferred: Decimal | None = None  # set for P4
    twenty_pct_rule_passed: bool | None = None
    period_rule_passed: bool | None = None
    income_change_pct: float | None = None
    per_member_income: Decimal | None = None
    proposed_deduction_rate_pct: float | None = None
    feasible: bool = True
    reason: str | None = None


class BilingualRationale(BaseModel):
    """Human-readable rationale in both English and Arabic."""
    rationale_en: str
    rationale_ar: str
    reasoning: str                  # 2–3 sentence plain English explanation
    reasoning_ar: str
    case_summary: str               # applicant situation summary (EN)
    case_summary_ar: str


class ADDMandate(BaseModel):
    """Auto Direct Debit mandate generated on approval.
    Authorises MOEI bank to deduct the agreed EMI automatically.
    Generated by A6 for all auto-approved cases (P1, P2, P3, P4).
    Not generated for P5 (human review) — officer handles mandate
    after human decision.
    Cites: CHANGE 3 — ADD Signature.
    """
    mandate_id: str                  # generated: "ADD-{application_id}"
    beneficiary_id: str
    emirates_id: str
    bank_name: str
    account_number_masked: str       # last 4 digits only
    agreed_emi: Decimal
    first_deduction_date: date
    mandate_status: Literal[
        "PENDING_SIGNATURE",
        "SIGNED",
        "REJECTED_BY_BENEFICIARY",
    ]
    generated_at: datetime
    signed_at: datetime | None = None
    mandate_text_en: str             # human-readable mandate text (EN)
    mandate_text_ar: str             # human-readable mandate text (AR)


class FinalRecommendation(BaseModel):
    """Complete output from A6 (Decision & Rationale Agent).
    Written to the recommendations and applications tables in Supabase."""
    application_id: str
    path_taken: Literal["P1", "P2", "P3", "P4", "P5"]
    plan: ReschedulingPlan
    rationale: BilingualRationale
    confidence_score: int            # 0–99
    risk_level: Literal["low", "medium", "high"]
    final_decision: str
    decision_rationale: str          # plain English for officer dashboard
    human_review_required: bool
    generated_at: datetime
    add_mandate: ADDMandate | None = None
    # None only when path == P5 (human review)
